# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MILIKET' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MILIKET
  pod 'GoogleMaps'
  pod 'DGElasticPullToRefresh'

  target 'MILIKETTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MILIKETUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
